baseURL = 'https://travels.loganfamily.co.uk/'
locale = 'en-gb'
title = 'Logan Van Travels'
theme = 'ananke'
summaryLength = 25

[permalinks]
  posts = '/:slug/'

[params]
  mainSections = ["posts"]

[params.ananke.pages]
  show_list_images = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Trips"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30
